name: Publish Package to npmjs
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: npm-publish
    steps:
      - uses: actions/checkout@v4
      - name: Enable corepack
        run: |
          corepack enable
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: ruby/setup-ruby@v1
      - uses: actions/cache@v4
        with:
          path: ${{ env.GEM_HOME }}
          key: ${{ runner.os }}
      - name: "Update CHANGELOG.md"
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.CHANGELOG_GITHUB_TOKEN }}
        run: gem install github_changelog_generator
      - name: "Commit CHANGELOG.md"
        run: |
          github_changelog_generator
          git add CHANGELOG.md
          if [ ! -n "$(git status -s)" ]; then
            echo "NOTHING TO COMMIT"
          else
            git config user.name vernak2539
            git config user.email "vernak2539@users.noreply.github.com"
            git commit -m "[skip ci] Update CHANGELOG.md"
            git push --no-verify
          fi
