name: Publish Package to npmjs
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: npm-publish
    steps:
      - uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable
      - uses: ruby/setup-ruby@v1
      - name: "Install github_changelog_generator"
        run: gem install github_changelog_generator
      - name: Generate CHANGELOG.md"
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.CHANGELOG_GITHUB_TOKEN }}
        run: github_changelog_generator
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Publish
        run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: "Commit CHANGELOG.md"
        run: |
          git add CHANGELOG.md
          if [ ! -n "$(git status -s)" ]; then
            echo "NOTHING TO COMMIT"
          else
            git config user.name "Alex Vernacchia"
            git config user.email "vernak2539@users.noreply.github.com"
            git commit -m "[skip ci] Update CHANGELOG.md"
            git push origin main --no-verify
          fi
