name: Update Changelog
on:
  workflow_dispatch:
    branches:
      - main

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    environment:
      name: npm-publish
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
      - name: "Install github_changelog_generator"
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.CHANGELOG_GITHUB_TOKEN }}
        run: gem install github_changelog_generator
      - name: "Update CHANGELOG.md"
        run: |
          github_changelog_generator
          git add CHANGELOG.md
      - name: "Commit changes"
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_prefix: "[skip ci]"
          commit_message: "Update CHANGELOG.md"
