name: Update Changelog
on:
  workflow_dispatch

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    environment:
      name: npm-publish
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
      - name: "Update CHANGELOG.md"
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.CHANGELOG_GITHUB_TOKEN }}
        run: gem install github_changelog_generator
      - name: "Commit CHANGELOG.md"
        run: |
          github_changelog_generator
          git add CHANGELOG.md
          if [ ! -n "$(git status -s)" ]; then
            echo "NOTHING TO COMMIT"
          else
            git config user.name vernak2539
            git config user.email "vernak2539@users.noreply.github.com"
            git commit -m "[skip ci] Update CHANGELOG.md"
            git push --no-verify
          fi
